Allow root relative path to append
Pondorasti/remark-img-links pull request #1
Opened 2021-07-15 20:05 UTC by qinyiyao

A root relative path like `/image/1` will override the existing path on `https://example.com/assets/` and result in `https://example.com/image/1` when it makes more sense to be `https://example.com/assets/image/1`.

2021-07-16 01:37 UTC, Pondorasti requested changes
Thanks for contributing! Your changes look good to me, but I did make a small suggestion that should make the logic a bit more clear.

Also, can you please add a test [here](https://github.com/Pondorasti/remark-img-links/blob/fbbf2283ba6c47c9cf8526bcc1045c7a67f3162c/test.js#L25) based on your example. It should go something along the lines:

```javascript
t.plan(4)

....

remark()
    .use(imgLinks, { absolutePath: "https://cdn.domain.com/assets/" })
    .use(html)
    .process("![Screenshot](/images/screenshot.png)", (err, file) => {
      const expectedYield = '<p><img src="https://cdn.domain.com/assets/images/screenshot.png" alt="Screenshot"></p>\n'
      t.equal(String(file), expectedYield)
    })
```

2021-07-16 01:37 UTC, Pondorasti commented on index.js
> +    node.url = new URL(node.url.replace(/^\//, ""), options.absolutePath).href
```suggestion
    // Sanitize URL by removing leading `/`
    const relativeUrl = node.url.replace(/^\//, "")
    
    node.url = new URL(relativeUrl, options.absolutePath).href
```

2021-07-19 06:33 UTC, Pondorasti commented
Hey mate, I think you forgot to submit your PR for review again. Make sure to also update `t.plan(4)`.

2021-07-19 13:33 UTC, qinyiyao commented
Ah, thanks for the guidance!

2021-07-20 03:09 UTC, Pondorasti commented
LGTM!

2021-07-20 03:12 UTC, Pondorasti commented
My bad for closing the PR. My cat stepped on the computer and accidentally pressed the close button.

2021-07-20 03:12 UTC, Pondorasti approved these changes

2021-07-20 03:13 UTC, merged

2021-07-20 03:13 UTC, Pondorasti commented
Thanks for taking the time to contribute @qinyiyao, good job! 🚀

2021-07-20 03:39 UTC, Pondorasti commented
Your changes have been published to npm package registry under [v1.0.8](https://www.npmjs.com/package/@pondorasti/remark-img-links).